@baseUrl = http://localhost:3333

@ownerAuthToken = {{ownerAuthenticate.response.body.access_token}}

# @name createOwnerAccount
POST {{baseUrl}}/accounts/owner
Content-Type: application/json

{
	"name": "OWWWWNER",
	"cellphone": "(47) 992-254-980",
	"email": "ownerwithsameid@test.com",
	"password": "12344321"
}

###

# @name createAgentAccount
POST {{baseUrl}}/accounts/1/agent
Content-Type: application/json

{
	"name": "User test - Authentication",
	"cellphone": "(47) 992-654-563",
	"email": "userauth@test.com",
	"password": "userauth123"
}

###

# @name createCompanyAccount
POST {{baseUrl}}/accounts/company
Content-Type: application/json

{
	"name": "Alles Imóveis",
	"telephone": "(47) 3390-3242",
	"cellphone": "(47) 992-786-397",
	"email": "alles@imoveis.com",
	"zipCode": "89040-100",
	"addressNumber": "142",
	"addressComplement": "Sala 23",
	"password": "23842382"
}

###

# @name agentAuthenticate
POST {{baseUrl}}/agent/auth
Content-Type: application/json

{
	"email": "userauth@test.com",
	"password": "userauth123"
}

###

# @name ownerAuthenticate
POST {{baseUrl}}/owner/auth
Content-Type: application/json

{
	"email": "ownerwithsameid@test.com",
	"password": "12344321"
}

###

# @name companyAuthenticate
POST {{baseUrl}}/company/auth
Content-Type: application/json

{
	"email": "alles@imoveis.com",
	"password": "23842382"
}

###

# @name createApartment
POST {{baseUrl}}/create-apartment
Content-Type: application/json
Authorization: Bearer {{ownerAuthToken}}

{
	"zipCode": "89040-100",
	"addressNumber": "142",
	"addressComplement": "Sala 23",
	"amenities": "4",
	"areaSize": "50",
	"builtYear": "2020",
	"description": "Cozy apartment for a young couple",
	"imagesIds": [],
	"price": "1800",
	"sponsorId": "76964f51-f9a8-459a-ace5-41891da4a10e",
	"status": "FOR_RENT",
	"airConditioner": "1",
	"balcony": "1",
	"bathrooms": "2",
	"bedrooms": "2",
	"condominium": "Dove home",
	"condominiumTax": "200",
	"dinnerRoom": "1",
	"elevator": "1",
	"floors": "1",
	"furniture": true,
	"garage": "2",
	"gym": true,
	"heat": "1",
	"kitchen": "1",
	"laundry": "1",
	"livingRoom": "1",
	"playground": false,
	"pool": "1",
	"socialSpace": true
}

###

# @name createLoft
POST {{baseUrl}}/create-loft
Content-Type: application/json
Authorization: Bearer {{ownerAuthToken}}

{
	"zipCode": "89120-000",
	"addressComplement": "",
	"addressNumber": "192",
	"amenities": "3",
	"areaSize": "45",
	"builtYear": "2023",
	"description": "Small loft",
	"imagesIds": [],
	"price": "2000",
	"sponsorId": "76964f51-f9a8-459a-ace5-41891da4a10e",
	"status": "FOR_RENT",
	"type": "ResidentialType.LOFT",
	"airConditioner": "1",
	"balcony": "0",
	"bathrooms": "1",
	"bedrooms": "1",
	"condominium": "Loft paradise",
	"condominiumTax": "800",
	"dinnerRoom": "0",
	"elevator": "2",
	"floors": "1",
	"furniture": true,
	"garage": "1",
	"gym": true,
	"heat": "1",
	"kitchen": "1",
	"laundry": "1",
	"livingRoom": "1",
	"playground": false,
	"pool": "1",
	"socialSpace": true
}

###

# @name createStudio
POST {{baseUrl}}/create-studio
Content-Type: application/json
Authorization: Bearer {{ownerAuthToken}}

{
	"zipCode": "89120-000",
	"addressComplement": "",
	"addressNumber": "2423",
	"amenities": "3",
	"areaSize": "45",
	"builtYear": "2022",
	"description": "Tiny studio",
	"imagesIds": [],
	"price": "2000",
	"sponsorId": "76964f51-f9a8-459a-ace5-41891da4a10e",
	"status": "FOR_RENT",
	"airConditioner": "1",
	"balcony": "0",
	"bathrooms": "1",
	"bedrooms": "1",
	"condominium": "Studio's point",
	"condominiumTax": "800",
	"dinnerRoom": "0",
	"elevator": "2",
	"floors": "1",
	"furniture": true,
	"garage": "1",
	"gym": true,
	"heat": "1",
	"kitchen": "1",
	"laundry": "1",
	"livingRoom": "1",
	"playground": false,
	"pool": "1",
	"socialSpace": true
}

###

# @name createHouse
POST {{baseUrl}}/create-house
Content-Type: application/json
Authorization: Bearer {{ownerAuthToken}}

{
	"zipCode": "89120-000",
	"addressComplement": "Brodwood way",
	"addressNumber": "938",
	"amenities": "8",
	"areaSize": "45",
	"builtYear": "2022",
	"description": "Nice house close to the lake",
	"imagesIds": [],
	"price": "2000",
	"sponsorId": "76964f51-f9a8-459a-ace5-41891da4a10e",
	"status": "FOR_BUY",
	"airConditioner": "1",
	"balcony": "0",
	"bathrooms": "1",
	"bedrooms": "1",
	"condominium": "Decent house for a small family",
	"condominiumTax": "800",
	"dinnerRoom": "0",
	"elevator": "2",
	"floors": "2",
	"furniture": true,
	"garage": "1",
	"gym": true,
	"heat": "1",
	"kitchen": "1",
	"laundry": "1",
	"livingRoom": "1",
	"playground": false,
	"pool": "1",
	"socialSpace": true,
	"deck": true,
	"porch": false,
	"backyard": true,
	"driveWay": true,
	"frontYard": true
}

###

# @name createCommercialRoom
POST {{baseUrl}}/create-commercial-room
Content-Type: application/json
Authorization: Bearer {{ownerAuthToken}}

{
	"zipCode": "89120-000",
	"addressComplement": "Room A43",
	"addressNumber": "9123",
	"areaSize": "200",
	"builtYear": "2021",
	"description": "Great commercial room for you business",
	"imagesIds": [],
	"internetAccess": true,
	"office": true,
	"furniture": true,
	"price": "2800",
	"restRoom": "4",
	"securitySystem": true,
	"sponsorId": "76964f51-f9a8-459a-ace5-41891da4a10e",
	"floors": "1",
	"status": "FOR_RENT"
}

###

# @name createHangar
POST {{baseUrl}}/create-hangar
Content-Type: application/json
Authorization: Bearer {{ownerAuthToken}}

{
	"zipCode": "89120-000",
	"addressComplement": "Industrial area",
	"addressNumber": "429",
	"areaSize": "3500",
	"builtYear": "2016",
	"description": "Big hangar, perfect for your storage company",
	"imagesIds": [],
	"internetAccess": true,
	"office": true,
	"parkingLot": true,
	"price": "1600.000",
	"restRoom": "4",
	"securitySystem": true,
	"sponsorId": "76964f51-f9a8-459a-ace5-41891da4a10e",
	"floors": "1",
	"status": "FOR_BUY"
}